# Generated by Django 5.0.6 on 2024-06-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvisuals', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='/hw5_final/media/products/canon.jpg', upload_to='products'),
        ),
    ]
