# Generated by Django 5.0.6 on 2024-06-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvisuals', '0003_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='displayc',
            field=models.TextField(default='ok'),
        ),
    ]
