# Generated by Django 5.0.6 on 2024-06-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvisuals', '0005_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(default='/hw5_final/media/products/canon.jpg', upload_to='products'),
        ),
    ]
