# Generated by Django 5.0.6 on 2024-06-22 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mvisuals', '0007_post_foto_post_slika'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='displayc',
            new_name='display',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='foto',
            new_name='image1',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='image2',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='photo',
            new_name='image3',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='slika',
            new_name='image4',
        ),
    ]
