# Generated by Django 5.0.6 on 2024-06-22 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvisuals', '0008_rename_displayc_post_display_rename_foto_post_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='display',
            field=models.TextField(default='Display Default'),
        ),
    ]
